export const RESET_TIMERS = "RESET_TIMERS";
export const START_TIMER = "START_TIMER";
export const TOGGLE_POMODORO_LABEL = "TOGGLE_POMODORO_LABEL";
export const TOGGLE_ISBUSY = "TOGGLE_ISBUSY";
export const SET_SESSION_COUNT = "SET_SESSION_COUNT";
export const RESET_SESSION = "RESET_SESSION";
export const RESET_TOTAL_SESSION_TIME = "RESET_TOTAL_SESSION_TIME";
